### ANKexplorer: Exploring the diversity of ANK repeats in the Podospora anserina species complex
# ===========================================================================
# Sandra Lorena Ament Velasquez
# 2024-08-13
# ++++++++++++++++++++++++++++++++++++++++++++++

# Input files
basealignment: "data/Pa_3_8560_haplotypes_al_trim3_reAl_nom_noGuides_noemptycols.fa"

# Scripts
descriptor: "scripts/REPEATdescriptor.py"
REPEAT_LOGO: "scripts/REPEAT_LOGO.R"

## Variables
GENE: "Pa_3_8560"

# Definition of the repeats
REGEX: '([\w]{1})(G|R|K|E)([\w]{2})(P|I|A)(L|S)([\w]{2})(A|R)([\w]{5})(E|L|K|W)([\w]{3})(R|K|Q)([LFIT]{3})([\w]{3})(A|V|T)(D|N)(I|P|R)([\w]{3})(D|N|S|T)([\w]{1})'
REPLEN: 33
REPMINLEN: 33
REPMAXLEN: 33

# The amino acid positions used to classify the repeats (influenced by the REGEX definition of the repeat)
AMINOS: ['1-3-4-5-7-8-10-11-12-14-16-29-31']