### NLRvsRandomGenes: A pipeline to compare NLRs from randomly selected genes in the Podospora anserina species complex
# ===========================================================================
# Sandra Lorena Ament Velasquez
# 2026/05/31
# ++++++++++++++++++++++++++++++++++++++++++++++

# Input metadata
randomfile: "data/RandomGenesList.txt"
HICfile: "data/HICGenesList.txt"
NLRfile: "data/LICGenesList.txt"
geneevo: "data/EvolutionAllGenes.csv"
expansions: "data/GeneFamilyExpansions.txt" # PFAM counts of the all Podospora species

path2alignments: "data"

# Tajima calculated in 10Kb windows with less than 50% missing data
FULLTajima: "../IntroRegions/data/WageningenTajimaMin5Kb.bed"

ANNOTATION: "../IntroRegions/data/Podan2.nice-3.02.gff3"
refgenome: "path/to/Podan2_AssemblyScaffoldsmt.fa"
TEs: "path/to/Podan2.repeatmasker.gff3"

winsize: 2000

PlotBalancingSelection: "scripts/PlotBalancingSelection.R"
PiDistNLRvsRandom: "scripts/PiDistNLRvsRandom.R"
NLRdynamics: "scripts/NLRdynamics.R"


